/* sccsdata.c - sccs data file for arg generated by mksccs */

/* @(#)sccsdata.c	1.26 4/6/95 */
char arg_sccsdata_c_rcsid[] = "$Id$";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  Makefile 1.17:
 *      Change checksccs and CHECKSCCS to sccs_check and SCCS_CHECK.
 *      Change install to ${INSTALL}, with INSTALL set to ucbinstall.
 *  
 */

const char *arg__sccsdata[] = {
	"arg version 1.26 (build date: Sun Jun 4 22:40:57 BST 1995)",
	"@{$arg$}: sccsdata.c 1.26 ",
	"@{$arg$}: arg_brace.c 1.10 ",
	"@{$arg$}: arg_dir.c 1.12 ",
	"@{$arg$}: arg_glob.c 1.12 ",
	"@{$arg$}: arg_lparse.c 1.11 ",
	"@{$arg$}: arg_match.c 1.9 ",
	"@{$arg$}: arg_quote.c 1.13 ",
	"@{$arg$}: arg_redir.c 1.13 ",
	"@{$arg$}: arg_user.c 1.13 ",
	"@{$arg$}: arg_vec.c 1.9 ",
	"@{$arg$}: arg_version.c 1.6 ",
	"@{$arg$}: testarg.c 1.10 ",
	"@{$arg$}: arg.h 1.7 ",
	"@{$arg$}: sccsdata.h 1.2 ",
	"@{$arg$}: Makefile 1.17 ",
};
