/* sccsdata.c - sccs data file for Men3wn generated by mksccs */

/* @(#)sccsdata.c	1.34 4/6/95 */
char Men3wn_sccsdata_c_rcsid[] = "$Id$";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  sccsdata.h 1.2:
 *      Replace _Men3wn_sccsdata with Men3wn__sccsdata.
 *  
 *  mdisplay.c 1.14:
 *      Replace _Men3wn_sccsdata with Men3wn__sccsdata.
 *  
 *  Makefile 1.16:
 *      Change checksccs and CHECKSCCS to sccs_check and SCCS_CHECK.
 *      Change install to ${INSTALL}, with INSTALL set to ucbinstall.
 *  
 */

const char *Men3wn__sccsdata[] = {
	"Men3wn version 1.34 (build date: Sun Jun 4 22:38:13 BST 1995)",
	"@{$Men3wn$}: sccsdata.c 1.34 ",
	"@{$Men3wn$}: marea.c 1.7 ",
	"@{$Men3wn$}: mclose.c 1.7 ",
	"@{$Men3wn$}: mcreate.c 1.10 ",
	"@{$Men3wn$}: mdisplay.c 1.14 ",
	"@{$Men3wn$}: mdup.c 1.10 ",
	"@{$Men3wn$}: mfmodes.c 1.6 ",
	"@{$Men3wn$}: minfo.c 1.6 ",
	"@{$Men3wn$}: minsert.c 1.10 ",
	"@{$Men3wn$}: mnewcap.c 1.8 ",
	"@{$Men3wn$}: mopen.c 1.14 ",
	"@{$Men3wn$}: mperror.c 1.6 ",
	"@{$Men3wn$}: msize.c 1.8 ",
	"@{$Men3wn$}: mstdfont.c 1.6 ",
	"@{$Men3wn$}: wdbyte.c 1.10 ",
	"@{$Men3wn$}: menu3.h 1.11 ",
	"@{$Men3wn$}: menu_priv.h 1.6 ",
	"@{$Men3wn$}: sccsdata.h 1.2 ",
	"@{$Men3wn$}: wdbyte.h 1.4 ",
	"@{$Men3wn$}: Makefile 1.16 ",
};
