/* sccsdata.c - sccs data file for med3 generated by mksccs */

/* @(#)sccsdata.c	1.22 10/1/95 */
char med3_sccsdata_c_rcsid[] = "$Id$";

#ifndef __STDC__
#define const
#endif

const char *med3__sccsdata[] = {
	"med3 version 2.0 (build date: Tue Jan 10 10:03:27 GMT 1995)",
	"@{$med3$}: sccsdata.c 1.0 ",
	"@{$med3$}: med3.h 1.0 ",
	"@{$med3$}: README 1.0 ",
	"@{$med3$}: bmdiv.c 1.0 ",
	"@{$med3$}: bmenu.c 1.0 ",
	"@{$med3$}: bmenu.h 1.0 ",
	"@{$med3$}: bmstack.c 1.0 ",
	"@{$med3$}: box.c 1.0 ",
	"@{$med3$}: coords.c 1.0 ",
	"@{$med3$}: cpats.c 1.0 ",
	"@{$med3$}: cursor.c 1.0 ",
	"@{$med3$}: cursors.h 1.0 ",
	"@{$med3$}: font.h 1.0 ",
	"@{$med3$}: fonts.c 1.0 ",
	"@{$med3$}: layout.h 1.0 ",
	"@{$med3$}: med3.c 1.0 ",
	"@{$med3$}: med3.h 1.0 ",
	"@{$med3$}: menu.c 1.0 ",
	"@{$med3$}: menu_priv.h 1.0 ",
	"@{$med3$}: mhole.c 1.0 ",
	"@{$med3$}: rvals.c 1.0 ",
	"@{$med3$}: rw.c 1.0 ",
	"@{$med3$}: strings.c 1.0 ",
	"@{$med3$}: makefile 1.0 ",
};

const char *
med3_version()
{
	return med3__sccsdata[0];
}
