/* sccsdata.c - sccs data file for obj generated by mksccs */

/* @(#)sccsdata.c	1.36 4/6/95 */
char obj_sccsdata_c_rcsid[] = "$Id$";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  Makefile 1.15:
 *      Change checksccs and CHECKSCCS to sccs_check and SCCS_CHECK.
 *      Change install to ${INSTALL}, with INSTALL set to ucbinstall.
 *  
 */

const char *obj__sccsdata[] = {
	"obj version 1.36 (build date: Sun Jun 4 22:40:13 BST 1995)",
	"@{$obj$}: sccsdata.c 1.36 ",
	"@{$obj$}: o_chds.c 1.17 ",
	"@{$obj$}: o_def.c 1.14 ",
	"@{$obj$}: o_disp.c 1.13 ",
	"@{$obj$}: o_globals.c 1.10 ",
	"@{$obj$}: o_lptrs.c 1.11 ",
	"@{$obj$}: o_mkobj.c 1.9 ",
	"@{$obj$}: o_sel.c 1.18 ",
	"@{$obj$}: o_text.c 1.1 ",
	"@{$obj$}: fed.c 1.25 ",
	"@{$obj$}: newtb.c 1.12 ",
	"@{$obj$}: mhole.c 1.13 ",
	"@{$obj$}: fed.h 1.10 ",
	"@{$obj$}: mhole.h 1.2 ",
	"@{$obj$}: newtb.h 1.5 ",
	"@{$obj$}: o_disp.h 1.2 ",
	"@{$obj$}: o_lptrs.h 1.2 ",
	"@{$obj$}: o_mkobj.h 1.4 ",
	"@{$obj$}: o_priv.h 1.7 ",
	"@{$obj$}: o_sel.h 1.4 ",
	"@{$obj$}: obj.h 1.15 ",
	"@{$obj$}: sccsdata.h 1.2 ",
	"@{$obj$}: doc/tech.ms 1.1 ",
	"@{$obj$}: Makefile 1.15 ",
};
