.TH CI_COMPILE 2 "April 11, 1999" "UPS 3.x" "C Interpreter API"
.SH NAME
ci_free_linkinfo - Free a byte-code structure.
.SH SYNOPSIS
.B #include <mtrprog/ifdefs.h>
.br
.B #include <local/ukcprog.h>
.br
.B #include <ups.h>
.br
.B #include <symtab.h>
.br
.B #include <ci.h>
.br
.B #include <xc_opcodes.h>
.br
.B #include <xc_machine.h>
.br
.B #include <xc_builtins.h>
.br
.B #include <cc.h>
.sp
\fBvoid 
.br
ci_free_linkinfo(\fIli\fB)
.br
linkinfo_t *\fIli\fB;
.sp
.fi
.SH DESCRIPTION
This function frees all memory allocated to the byte-code structure.
.PP
.SH SEE ALSO
.BR ci_compile (2)
