/* sccsdata.c - sccs data file for ups generated by mksccs */

/* @(#)sccsdata.c	3.14 21/6/95 */
char ups_sccsdata_c_rcsid[] = "$Id$";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  If we can't find a .o file under the N_OBJ path, look for it in the
 *  same places we look for source files.
 *  Switch from block editing cursor to narrow marker bar.
 *  Under Solaris 2, check for execute permission before execing the target.
 *  Fix parsing of integer constants in the C interpreter.
 *  Automatically display source when a single stack object is selected.
 *  Minor updates to the man page.
 *  
 *  ao_symscan.c 1.3:
 *      make_stf(): stf_objpath field replaced by stf_objpath_hint and stf_objname.
 *      scan_symtab(): Take extra name parameter - needed when called from
 *      scan_dot_o_file().
 *      note_ofile_function(): Take extra name parameter (see above).
 *      adjust_fil_vars_addr_base(): Skip files with stf NULL.
 *  
 *  ao_symscan.h 1.2:
 *      Track change to scan_symtab() prototype.
 *  
 *  ao_procfs.c 1.3:
 *      procfs_create_child(): Don't attempt to vfork() and exec() if access()
 *      reports that the target is not executable.
 *  
 *  ao_elfsym.c 1.3:
 *      scan_index_syms(): Don't try to set *p_mainfunc_name if it is NULL.
 *        Only look at first N_OPT after an N_SO.  Store N_OBJ path_hint and
 *        name seperately, so scan_dot_o_file_symtab() can try various places
 *        for the .o file.
 *      setup_ofile_symio(): Make copy of el->path, as it is now temporary.
 *      scan_dot_o_file_symtab(): Locate .o files based on the path hint and the
 *        list of source file dirs.
 *      elf_scan_then_setup_symio(): Use the source file stf when passed a
 *        header file fil struct.
 *  
 *  srcpath.c 1.3:
 *      srcpath_resolve_path(): New public function to search for a file in
 *      the same list of directories we search for source files.  Used to
 *      locate .o files under Solaris 2.
 *  
 *  srcpath.h 1.2:
 *      Add prototype for new function srcpath_resolve_path().
 *  
 *  cx_wsym.c 1.4:
 *      enter_type(): Change keylen parameter from int to size_t to track
 *        change to hash_apply().
 *  
 *  ao_text.c 1.6:
 *      scan_ao_symtab(): Track change to scan_symtab().
 *  
 *  ao_syms.h 1.4:
 *      stf_t: Replace stf_objpath member with stf_objpath_hint and
 *        stf_objname.  This is so ao_elfsym.c can locate .o files more
 *        intelligently.
 *  
 *  ci_lex.c 1.24:
 *      yylex(): Avoid silently getting the wrong value for integer constants
 *        like 0xffffffff.  C integer lexing code still needs work though.
 *  ci_lex.c 1.25:
 *      ci_lex(): Call new function convert_number() rather than strtoul(), as
 *        SunOS 4.X doesn't have strtoul() (plus, we can do better error
 *        messages).
 *  
 *  ui_layout.c 1.32:
 *      display_area_input(): Automatically display source when a single stack
 *        object is selected.
 *  
 *  obj_stack.c 1.21:
 *      maybe_show_stack_entry_source(): New function to automatically display
 *        source when a single stack object is selected.
 *  
 *  obj_stack.h 1.12:
 *      Add prototype for new function maybe_show_stack_entry_source().
 *  
 *  doc/ups.man 1.17:
 *      Describe xterm-like clicking in the scroll bar.
 *      Describe new meanings for the source window Up and Down menu items.
 *      s/editing cursor/marker bar/ throughout.
 *  
 */

const char *ups__sccsdata[] = {
	"ups version  3.38beta1 (build date: Fri Oct 25 16:57:55 BST 2002)",
	"@{$ups$}: sccsdata.c 3.14 ",
	"@{$ups$}: st_debug.c 1.1 ",
	"@{$ups$}: st_lookup.c 1.8 ",
	"@{$ups$}: st_fmap.c 1.22 ",
	"@{$ups$}: st_util.c 1.5 ",
	"@{$ups$}: st_cb.c 1.22 ",
	"@{$ups$}: st_module.c 1.1 ",
	"@{$ups$}: ao_target.c 1.1 ",
	"@{$ups$}: ao_procfs.c 1.3 ",
	"@{$ups$}: ao_ptrace.c 1.2 ",
	"@{$ups$}: ao_core.c 1.5 ",
	"@{$ups$}: ao_symread.c 1.4 ",
	"@{$ups$}: ao_shlib.c 1.5 ",
	"@{$ups$}: ao_symload.c 1.9 ",
	"@{$ups$}: ao_symparse.c 1.7 ",
	"@{$ups$}: ao_symscan.c 1.3 ",
	"@{$ups$}: ao_symcb.c 1.2 ",
	"@{$ups$}: ao_aout.c 1.2 ",
	"@{$ups$}: ao_elfcore.c 1.1 ",
	"@{$ups$}: ao_elfread.c 1.2 ",
	"@{$ups$}: ao_elfsym.c 1.3 ",
	"@{$ups$}: ao_elflib.c 1.1 ",
	"@{$ups$}: ao_aflist.c 1.2 ",
	"@{$ups$}: ao_te.c 1.5 ",
	"@{$ups$}: ao_text.c 1.6 ",
	"@{$ups$}: ao_stack.c 1.3 ",
	"@{$ups$}: as_vax.c 1.17 ",
	"@{$ups$}: as_68020.c 1.17 ",
	"@{$ups$}: as_mips.c 1.9 ",
	"@{$ups$}: as_clipper.c 1.9 ",
	"@{$ups$}: as_sparc.c 1.16 ",
	"@{$ups$}: ui_iploop.c 1.41 ",
	"@{$ups$}: ui_layout.c 1.32 ",
	"@{$ups$}: ui_menu.c 1.27 ",
	"@{$ups$}: ui_misc.c 1.21 ",
	"@{$ups$}: ui_src.c 1.40 ",
	"@{$ups$}: va_decl.c 1.30 ",
	"@{$ups$}: va_edit.c 1.31 ",
	"@{$ups$}: va_menu.c 1.34 ",
	"@{$ups$}: va_type.c 1.21 ",
	"@{$ups$}: va_val.c 1.39 ",
	"@{$ups$}: va_expr.c 1.26 ",
	"@{$ups$}: va_state.c 1.8 ",
	"@{$ups$}: va_format.c 1.3 ",
	"@{$ups$}: obj_bpt.c 1.42 ",
	"@{$ups$}: obj_signal.c 1.27 ",
	"@{$ups$}: obj_misc.c 1.26 ",
	"@{$ups$}: obj_buildf.c 1.31 ",
	"@{$ups$}: obj_target.c 1.28 ",
	"@{$ups$}: obj_env.c 1.15 ",
	"@{$ups$}: obj_stack.c 1.21 ",
	"@{$ups$}: obj_util.c 1.4 ",
	"@{$ups$}: state.c 1.13 ",
	"@{$ups$}: reg.c 1.18 ",
	"@{$ups$}: cursors.c 1.14 ",
	"@{$ups$}: menudata.c 1.22 ",
	"@{$ups$}: tdr.c 1.19 ",
	"@{$ups$}: util.c 1.5 ",
	"@{$ups$}: bp.c 1.21 ",
	"@{$ups$}: exec.c 1.43 ",
	"@{$ups$}: trun_ss.c 1.22 ",
	"@{$ups$}: trun_j.c 1.32 ",
	"@{$ups$}: data.c 1.17 ",
	"@{$ups$}: target.c 1.12 ",
	"@{$ups$}: as_mi.c 1.25 ",
	"@{$ups$}: expr.c 1.39 ",
	"@{$ups$}: srcwin.c 1.7 ",
	"@{$ups$}: srcbuf.c 1.3 ",
	"@{$ups$}: srcpath.c 1.3 ",
	"@{$ups$}: printf.c 1.24 ",
	"@{$ups$}: config.c 1.5 ",
	"@{$ups$}: ups.c 1.53 ",
	"@{$ups$}: cc.c 1.3 ",
	"@{$ups$}: xc_symparse.c 1.3 ",
	"@{$ups$}: xc_text.c 1.4 ",
	"@{$ups$}: xc_load.c 1.5 ",
	"@{$ups$}: xc_machine.c 1.5 ",
	"@{$ups$}: xc_builtins.c 1.11 ",
	"@{$ups$}: ci_types.c 1.18 ",
	"@{$ups$}: ci_lex.c 1.25 ",
	"@{$ups$}: ci_stm.c 1.14 ",
	"@{$ups$}: ci_decl.c 1.23 ",
	"@{$ups$}: ci_func.c 1.20 ",
	"@{$ups$}: ci_util.c 1.25 ",
	"@{$ups$}: ci_expr.c 1.22 ",
	"@{$ups$}: ci_showexpr.c 1.13 ",
	"@{$ups$}: ci_constexpr.c 1.16 ",
	"@{$ups$}: ci_compile.c 1.23 ",
	"@{$ups$}: ci_compile_expr.c 1.27 ",
	"@{$ups$}: ci_opcodes.c 1.22 ",
	"@{$ups$}: ci_init.c 1.17 ",
	"@{$ups$}: cx.c 1.16 ",
	"@{$ups$}: cx_link.c 1.4 ",
	"@{$ups$}: cx_symio.c 1.3 ",
	"@{$ups$}: cx_wsym.c 1.4 ",
	"@{$ups$}: cx_onefile.c 1.2 ",
	"@{$ups$}: xc.c 1.3 ",
	"@{$ups$}: cg.c 1.1 ",
	"@{$ups$}: gd_driver.c 1.10 ",
	"@{$ups$}: tops-gdb.c 1.1 ",
	"@{$ups$}: tops-native.c 1.2 ",
	"@{$ups$}: ci_parse.y 1.15 ",
	"@{$ups$}: ao.h 1.1 ",
	"@{$ups$}: ao_aflist.h 1.1 ",
	"@{$ups$}: ao_aout.h 1.1 ",
	"@{$ups$}: ao_asm.h 1.1 ",
	"@{$ups$}: ao_core.h 1.3 ",
	"@{$ups$}: ao_elfcore.h 1.1 ",
	"@{$ups$}: ao_elflib.h 1.1 ",
	"@{$ups$}: ao_elfpriv.h 1.2 ",
	"@{$ups$}: ao_elfread.h 1.1 ",
	"@{$ups$}: ao_elfsym.h 1.2 ",
	"@{$ups$}: ao_execinfo.h 1.1 ",
	"@{$ups$}: ao_ifdefs.h 1.1 ",
	"@{$ups$}: ao_procfs.h 1.1 ",
	"@{$ups$}: ao_ptrace.h 1.1 ",
	"@{$ups$}: ao_shlib.h 1.2 ",
	"@{$ups$}: ao_stack.h 1.1 ",
	"@{$ups$}: ao_symcb.h 1.1 ",
	"@{$ups$}: ao_symload.h 1.5 ",
	"@{$ups$}: ao_symparse.h 1.3 ",
	"@{$ups$}: ao_symread.h 1.4 ",
	"@{$ups$}: ao_syms.h 1.4 ",
	"@{$ups$}: ao_symscan.h 1.2 ",
	"@{$ups$}: ao_target.h 1.3 ",
	"@{$ups$}: ao_te.h 1.1 ",
	"@{$ups$}: ao_text.h 1.2 ",
	"@{$ups$}: as.h 1.5 ",
	"@{$ups$}: breakpoint.h 1.6 ",
	"@{$ups$}: cc.h 1.1 ",
	"@{$ups$}: ci.h 1.20 ",
	"@{$ups$}: ci_compile.h 1.10 ",
	"@{$ups$}: ci_compile_expr.h 1.4 ",
	"@{$ups$}: ci_constexpr.h 1.3 ",
	"@{$ups$}: ci_decl.h 1.6 ",
	"@{$ups$}: ci_expr.h 1.6 ",
	"@{$ups$}: ci_func.h 1.2 ",
	"@{$ups$}: ci_init.h 1.2 ",
	"@{$ups$}: ci_lex.h 1.3 ",
	"@{$ups$}: ci_opcodes.h 1.4 ",
	"@{$ups$}: ci_parse.h 1.10 ",
	"@{$ups$}: ci_showexpr.h 1.2 ",
	"@{$ups$}: ci_stm.h 1.2 ",
	"@{$ups$}: ci_tokens.h 1.2 ",
	"@{$ups$}: ci_types.h 1.4 ",
	"@{$ups$}: ci_util.h 1.9 ",
	"@{$ups$}: config.h 1.2 ",
	"@{$ups$}: core.h 1.6 ",
	"@{$ups$}: cursors.h 1.5 ",
	"@{$ups$}: cx_libfuncs.h 1.6 ",
	"@{$ups$}: cx_libvars.h 1.4 ",
	"@{$ups$}: cx_link.h 1.3 ",
	"@{$ups$}: cx_symio.h 1.1 ",
	"@{$ups$}: cx_wsym.h 1.1 ",
	"@{$ups$}: data.h 1.6 ",
	"@{$ups$}: debug.h 1.7 ",
	"@{$ups$}: dx.h 1.1 ",
	"@{$ups$}: elfstab.h 1.1 ",
	"@{$ups$}: exec.h 1.13 ",
	"@{$ups$}: expr.h 1.7 ",
	"@{$ups$}: gd.h 1.1 ",
	"@{$ups$}: menudata.h 1.7 ",
	"@{$ups$}: mips_frame.h 1.2 ",
	"@{$ups$}: mreg.h 1.13 ",
	"@{$ups$}: obj_bpt.h 1.14 ",
	"@{$ups$}: obj_buildf.h 1.9 ",
	"@{$ups$}: obj_env.h 1.7 ",
	"@{$ups$}: obj_misc.h 1.11 ",
	"@{$ups$}: obj_signal.h 1.12 ",
	"@{$ups$}: obj_stack.h 1.12 ",
	"@{$ups$}: obj_target.h 1.11 ",
	"@{$ups$}: obj_util.h 1.4 ",
	"@{$ups$}: objtypes.h 1.13 ",
	"@{$ups$}: output.h 1.5 ",
	"@{$ups$}: printf.h 1.4 ",
	"@{$ups$}: proc.h 1.15 ",
	"@{$ups$}: reg.h 1.11 ",
	"@{$ups$}: sccsdata.h 1.2 ",
	"@{$ups$}: srcbuf.h 1.2 ",
	"@{$ups$}: srcpath.h 1.2 ",
	"@{$ups$}: srcwin.h 1.3 ",
	"@{$ups$}: st.h 1.8 ",
	"@{$ups$}: state.h 1.10 ",
	"@{$ups$}: symtab.h 1.28 ",
	"@{$ups$}: target.h 1.6 ",
	"@{$ups$}: tdr.h 1.9 ",
	"@{$ups$}: trun.h 1.9 ",
	"@{$ups$}: ui.h 1.25 ",
	"@{$ups$}: ui_priv.h 1.13 ",
	"@{$ups$}: ups.h 1.7 ",
	"@{$ups$}: util.h 1.4 ",
	"@{$ups$}: va.h 1.12 ",
	"@{$ups$}: va_priv.h 1.15 ",
	"@{$ups$}: xc.h 1.1 ",
	"@{$ups$}: xc_builtins.h 1.1 ",
	"@{$ups$}: xc_load.h 1.3 ",
	"@{$ups$}: xc_machine.h 1.1 ",
	"@{$ups$}: xc_opcodes.h 1.2 ",
	"@{$ups$}: xc_symparse.h 1.1 ",
	"@{$ups$}: st_debug.h 1.1 ",
	"@{$ups$}: doc/ups.man 1.17 ",
	"@{$ups$}: doc/porting.ms 1.1 ",
	"@{$ups$}: doc/linking.ms 1.1 ",
	"@{$ups$}: doc/refs.refer 1.2 ",
	"@{$ups$}: Makefile 1.57 ",
};
