/* sccsdata.c - sccs data file for wn generated by mksccs */

/* @(#)sccsdata.c	1.86 4/6/95 */
char wn_sccsdata_c_rcsid[] = "$Id$";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  Makefile 1.34:
 *      Change checchecksccs and CHECKSCCS to sccs_check and SCCS_CHECK.
 *      Change install to ${INSTALL}, with INSTALL set to ucbinstall.
 *  
 */

const char *wn__sccsdata[] = {
	"wn version 1.86 (build date: Sun Jun 4 22:32:12 BST 1995)",
	"@{$wn$}: sccsdata.c 1.86 ",
	"@{$wn$}: framed.h 1.2 ",
	"@{$wn$}: wn_framed.h 1.2 ",
	"@{$wn$}: wn_sunframe.h 1.2 ",
	"@{$wn$}: sccsdata.h 1.2 ",
	"@{$wn$}: wn.h 1.23 ",
	"@{$wn$}: wn_bm.h 1.2 ",
	"@{$wn$}: wn_color.h 1.3 ",
	"@{$wn$}: wn_cu.h 1.4 ",
	"@{$wn$}: wn_event.h 1.4 ",
	"@{$wn$}: wn_icon.h 1.2 ",
	"@{$wn$}: wn_init.h 1.2 ",
	"@{$wn$}: wn_misc.h 1.6 ",
	"@{$wn$}: wn_priv.h 1.17 ",
	"@{$wn$}: wn_replay.h 1.4 ",
	"@{$wn$}: wn_rop.h 1.2 ",
	"@{$wn$}: wn_sc.h 1.2 ",
	"@{$wn$}: wn_win.h 1.4 ",
	"@{$wn$}: wn_xrop.h 1.2 ",
	"@{$wn$}: wn_color.c 1.16 ",
	"@{$wn$}: wn_cu.c 1.14 ",
	"@{$wn$}: wn_sc.c 1.14 ",
	"@{$wn$}: wn_font.c 1.19 ",
	"@{$wn$}: wn_event.c 1.46 ",
	"@{$wn$}: wn_rop.c 1.18 ",
	"@{$wn$}: wn_xrop.c 1.13 ",
	"@{$wn$}: wn_mrop.c 1.13 ",
	"@{$wn$}: wn_bm.c 1.13 ",
	"@{$wn$}: wn_misc.c 1.32 ",
	"@{$wn$}: wn_init.c 1.53 ",
	"@{$wn$}: wn_win.c 1.23 ",
	"@{$wn$}: wn_sunframe.c 1.16 ",
	"@{$wn$}: wn_framed.c 1.11 ",
	"@{$wn$}: wn_icon.c 1.18 ",
	"@{$wn$}: wn_replay.c 1.17 ",
	"@{$wn$}: doc/wn.tex 1.1 ",
	"@{$wn$}: doc/wn-list.tex 1.1 ",
	"@{$wn$}: edump.c 1.5 ",
	"@{$wn$}: framed.c 1.10 ",
	"@{$wn$}: testwn.c 1.25 ",
	"@{$wn$}: Makefile 1.34 ",
};
