/* sccsdata.c - sccs data file for ukcprog generated by mksccs */

/* @(#)sccsdata.c	1.22 10/1/95 */
char ukcprog_sccsdata_c_rcsid[] = "$Id$";

#include "ukcprog.h"

/*  Changes since the last version:
 *
 *  logf.c 1.20:
 *      Put #ifndef __FreeBSD__ round sys_errlist decl.
 *  
 *  formf.c 1.23:
 *      Put #ifndef __FreeBSD__ round sys_errlist decl.
 *  
 */

const char *ukcprog__sccsdata[] = {
	"ukcprog version 1.22 (build date: Tue Jan 10 10:03:27 GMT 1995)",
	"@{$ukcprog$}: sccsdata.c 1.22 ",
	"@{$ukcprog$}: ukcprog.h 1.34 ",
	"@{$ukcprog$}: alloc.c 1.10 ",
	"@{$ukcprog$}: e_malloc.c 1.9 ",
	"@{$ukcprog$}: e_realloc.c 1.8 ",
	"@{$ukcprog$}: errf.c 1.15 ",
	"@{$ukcprog$}: formf.c 1.23 ",
	"@{$ukcprog$}: panic.c 1.9 ",
	"@{$ukcprog$}: ssplit.c 1.7 ",
	"@{$ukcprog$}: strf.c 1.7 ",
	"@{$ukcprog$}: strnf.c 1.7 ",
	"@{$ukcprog$}: strsave.c 1.7 ",
	"@{$ukcprog$}: fpgetline.c 1.7 ",
	"@{$ukcprog$}: strtol.c 1.4 ",
	"@{$ukcprog$}: config.c 1.4 ",
	"@{$ukcprog$}: ip.c 1.6 ",
	"@{$ukcprog$}: ebuf.c 1.6 ",
	"@{$ukcprog$}: logf.c 1.20 ",
	"@{$ukcprog$}: doc/ukcprog.3 1.18 ",
	"@{$ukcprog$}: Makefile 1.21 ",
};

const char *
ukcprog_version()
{
	return ukcprog__sccsdata[0];
}
