/* sccsdata.c - sccs data file for edit generated by mksccs */

/* @(#)sccsdata.c	1.17 20/6/95 */
char edit_sccsdata_c_rcsid[] = "$Id$";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  win.c 1.11:
 *      Use a marker bar rather than a block cursor.
 *  
 */

const char *edit__sccsdata[] = {
	"edit version 1.17 (build date: Tue Jun 20 22:57:59 BST 1995)",
	"@{$edit$}: sccsdata.c 1.17 ",
	"@{$edit$}: edit.c 1.8 ",
	"@{$edit$}: display.c 1.10 ",
	"@{$edit$}: simplebuf.c 1.4 ",
	"@{$edit$}: win.c 1.11 ",
	"@{$edit$}: lbuf.c 1.5 ",
	"@{$edit$}: filebuf.c 1.6 ",
	"@{$edit$}: props.c 1.4 ",
	"@{$edit$}: util.c 1.4 ",
	"@{$edit$}: version.c 1.1 ",
	"@{$edit$}: flines.c 1.5 ",
	"@{$edit$}: sline.c 1.2 ",
	"@{$edit$}: render.c 1.5 ",
	"@{$edit$}: keymap.c 1.2 ",
	"@{$edit$}: testedit.c 1.12 ",
	"@{$edit$}: display.h 1.8 ",
	"@{$edit$}: edit.h 1.11 ",
	"@{$edit$}: filebuf.h 1.2 ",
	"@{$edit$}: lbuf.h 1.3 ",
	"@{$edit$}: sccsdata.h 1.1 ",
	"@{$edit$}: simplebuf.h 1.3 ",
	"@{$edit$}: win.h 1.7 ",
	"@{$edit$}: props.h 1.2 ",
	"@{$edit$}: textbuf.h 1.2 ",
	"@{$edit$}: render.h 1.2 ",
	"@{$edit$}: README 1.1 ",
	"@{$edit$}: Makefile 1.9 ",
};
